#!/bin/bash

echo shipobs start `date`
if [ ! -f /tmp/lock_shipobs ]; then
  touch /tmp/lock_shipobs

  cd /var/www/html/assets
  wget --user=2creek_madis_public --password='7bv56qp5Wdt3' 'https://madis-data.noaa.gov/madisPublic/cgi-bin/madisXmlPublicDir?rdr=&time=0&minbck=-180&minfwd=0&recwin=3&dfltrsel=0&state=AK&latll=0.0&lonll=0.0&latur=90.0&lonur=0.0&stanam=&stasel=0&pvdrsel=1&varsel=1&qcsel=1&xml=1&csvmiss=0&pvd=MARITIME&nvars=SLP&nvars=T&nvars=DD&nvars=FF&nvars=FFGUST&nvars=PSWDIR&nvars=PSWHT&nvars=PSWPER&nvars=SST&nvars=WAVEHT&nvars=WAVEPER' -O xml/shipobs.xml

  rm -f /tmp/lock_shipobs
fi
echo shipobs end `date`
